stages:
  - lint
  - test

flake8:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/flake8.txt
    - flake8 servicetrack

black:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black servicetrack

django:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements/test.txt
    - cd servicetrack
    - python3 manage.py test